### PR TITLE
Update notebooks to match format requirements

### PR DESCRIPTION
**Pull request by KumoLiu**
### Description
This PR updated several tutorials to match the format requirements of contribution guideline.
- [x] module tutorials
- [x] pathology
- [x] microscopy/multichannel_microscopy_classification.ipynb
- [x] full_gpu_inference_pipeline/client/non_ensemble/client.ipynb
- [x] federated_learning/openfl/openfl_mednist_2d_registration/workspace/Monai_MedNIST.ipynb
- [x] deployment

### Checks

- [x] Avoid including large-size files in the PR.
- [x] Clean up long text outputs from code cells in the notebook.
- [x] For security purposes, please check the contents and remove any sensitive info such as user names and private key.
- [x] Ensure (1) hyperlinks and markdown anchors are working (2) use relative paths for tutorial repo files (3) put figure and graphs in the `./figure` folder
- [x] Notebook runs automatically `./runner.sh -t <path to .ipynb file>`

### CODE REVIEW

**Review by wyli — APPROVED** [review]

**Comment by wyli** [comment]
I see permerge errors https://github.com/Project-MONAI/tutorials/actions/runs/3910825263/jobs/6683476358

perhaps this command can address them https://github.com/Project-MONAI/MONAI/blob/4b464e7b6bee1b52fa0be4d72a4662f384f095af/runtests.sh#L114-L119

**Comment by KumoLiu** [comment]
> I see permerge errors https://github.com/Project-MONAI/tutorials/actions/runs/3910825263/jobs/6683476358
> 
> perhaps this command can address them https://github.com/Project-MONAI/MONAI/blob/4b464e7b6bee1b52fa0be4d72a4662f384f095af/runtests.sh#L114-L119

Thanks, @wyli! It has been fixed according to your suggestions!

**Comment by wyli** [comment]
I'm merging this for now because there's a fix for runtests.sh, please raise more pull requests if @mingxin-zheng has more comments

**Comment by mingxin-zheng** [comment]
@wyli Thanks. I am on travel today and had limited access to internet. I will look at these notebooks and raise issues if there are any.

**Comment by mingxin-zheng** [comment]
Regarding the formats, everything looks good to me @KumoLiu . Thank you!

**Pull request merged**
