### PR TITLE
Update tumor detection pipline with new components

### LINKED ISSUE #636: [MONAI Pathology] Update tumor detection pipeline
There are going to be major changes in pathology components in MONAI, so the tumor detection pipeline needs to be updated with these new components.

### PR DESCRIPTION
**Pull request by drbeh**
Fixes #636 

### Description
Updates the ignite-based tumor detection pipeline that uses numpy and pytorch tensors with the new components in MONAI.

### Status
**Ready**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Do you also need to update the code under `tumor_detection/torch/` folder?

Thanks.

**Comment by drbeh** [comment]
> Hi @drbeh ,
> 
> Do you also need to update the code under `tumor_detection/torch/` folder?
> 
> Thanks.

Hey @Nic-Ma, yes of course. All the tumor detection tutorials need to be updated.

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Could you please help remove the 2 CSV files from the PR? It makes the PR around 200000 lines change.

Thanks.

**Comment by drbeh** [comment]
> Hi @drbeh ,
> 
> Could you please help remove the 2 CSV files from the PR? It makes the PR around 200000 lines change.
> 
> Thanks.

Hi @Nic-Ma,
Absolutely! I left them there for Ziyue while we were changing things.

**Review by Nic-Ma — APPROVED** [review]
Thanks for the update, looks good to me.
@wyli Do you have any other comments?

Thanks.

**Pull request merged**
