### PR TITLE
Update deepgrow notebooks

### LINKED ISSUE #169: deepgrow files not present
Deepgrow tutorials need files that are not present to run, see here: https://github.com/Project-MONAI/MONAI/runs/2243105725?check_suite_focus=true#step:6:298.

### PR DESCRIPTION
**Pull request by YuanTingHsieh**
Signed-off-by: YuanTingHsieh <yuantinghsieh@gmail.com>

Fixes #169 .

### Description
As suggested using gdown to download required files from the link @SachidanandAlle provided.

### Status
**Ready**

### Checks

- [x] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by wyli** [comment]
could you add a cell to ensure a compatible`gdown` is installed: 
```
!python -c "import monai" || pip install -q "monai-weekly[gdown, tqdm]"
```

**Comment by YuanTingHsieh** [comment]
Will do.
Do we want to include the output (those graphs and execution result of each cell) into the notebook?

**Comment by wyli** [comment]
thanks, I think we could remove the figures in the 3d notebook as they are too large. 2D looks great

**Review by wyli — APPROVED** [review]
thanks!

**Pull request merged**
