### PR TITLE
Add itkwidgets example in notebook

### PR DESCRIPTION
**Pull request by Nic-Ma**
### Description
This PR added `itkwidgets` example in the visualization tutorial.

### Status
**Ready**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by ericspod** [comment]
I'm not getting any display with `view` from itkwidgets. With the following in a cell:

```python
import monai
from itkwidgets import view
img,seg=monai.data.create_test_image_3d(128,128,128,5)
view(image=img*255, label_image=seg * 255, gradient_opacity=0.4)
```
I get no output as a result in Jupyter or Jupyterlab 3.1.7. I installed the itkwidgets package on top of whatever else was needed for MONAI 0.7.0 so am I missing something? It might just be a Jupyter version issue as discussed, all my Jupyter versions are:

```
IPython          : 7.29.0
ipykernel        : 6.4.1
ipywidgets       : 7.6.5
jupyter_client   : 7.0.1
jupyter_core     : 4.8.1
jupyter_server   : 1.4.1
jupyterlab       : 3.2.1
nbclient         : 0.5.3
nbconvert        : 6.1.0
nbformat         : 5.1.3
notebook         : 6.4.5
qtconsole        : not installed
traitlets        : 5.1.0

```

**Comment by aylward** [comment]
Regretfully Jupyter Lab 3 isn't supported, but it should work in notebooks.

Do the controls show up?   If so, please try switching to a 2D view (click on one of the cubes that has a yellow, red, or green face to switch to a 2D view).   Let me know if a 2D image shows.

If only a line of text appears, then I'll checkout your specific versions.   I'm running conda on Windows and the versions are a bit behind yours on some of those packages...I can dig into it.

**Comment by aylward** [comment]
We might want to also show off the checkerboard command for 2D/3D image comparison:

itkWidgets-Checkerboard

**Comment by aylward** [comment]
Ah - just saw that you're creating 5-channel data.  Can you try creating single-channel data or sending only one channel to the view() comment:

**Comment by ericspod** [comment]
Hi @aylward,
I ran the cell again and both image and segmentation have shape (128,128,128) so I don't think it's a channel problem. In Jupyter Notebook I tried adding a 1-size channel to the beginning and end without success for the whole volumes and 2D slices thereof. If I try it again in Jupyterlab it does say "loading widget..." as output but no more. I'm on Ubuntu 20.04.3 LTS.

<details>
<summary>My library versions for Python 3.8.12</summary>
<ul></li>
<li>_libgcc_mutex             0.1                        main  </li>
<li>_openmp_mutex             4.5                       1_gnu  </li>
<li>absl-py                   1.0.0                    pypi_0    pypi</li>
<li>anyio                     2.2.0            py38h06a4308_1  </li>
<li>appdirs                   1.4.4              pyhd3eb1b0_0  </li>
<li>argon2-cffi               20.1.0           py38h27cfd23_1  </li>
<li>async_generator           1.10               pyhd3eb1b0_0  </li>
<li>attrs                     21.2.0             pyhd3eb1b0_0  </li>
<li>babel                     2.9.1              pyhd3eb1b0_0  </li>
<li>backcall                  0.2.0              pyhd3eb1b0_0  </li>
<li>black                     19.10b0                    py_0  </li>
<li>blas                      1.0                         mkl  </li>
<li>bleach                    4.0.0              pyhd3eb1b0_0  </li>
<li>blosc                     1.21.0               h8c45485_0  </li>
<li>bottleneck                1.3.2            py38heb32a55_1  </li>
<li>brotli                    1.0.9                he6710b0_2  </li>
<li>brotlipy                  0.7.0           py38h27cfd23_1003  </li>
<li>brunsli                   0.1                  h2531618_0  </li>
<li>bzip2                     1.0.8                h7b6447c_0  </li>
<li>c-ares                    1.17.1               h27cfd23_0  </li>
<li>ca-certificates           2021.10.26           h06a4308_2  </li>
<li>cachetools                4.2.4                    pypi_0    pypi</li>
<li>certifi                   2021.10.8        py38h06a4308_0  </li>
<li>cffi                      1.14.6           py38h400218f_0  </li>
<li>cfitsio                   3.470                hf0d0db6_6  </li>
<li>charls                    2.2.0                h2531618_0  </li>
<li>charset-normalizer        2.0.4              pyhd3eb1b0_0  </li>
<li>click                     8.0.3              pyhd3eb1b0_0  </li>
<li>cloudpickle               2.0.0              pyhd3eb1b0_0  </li>
<li>colorcet                  2.0.6                    pypi_0    pypi</li>
<li>coverage                  5.5              py38h27cfd23_2  </li>
<li>cryptography              35.0.0           py38hd23ed53_0  </li>
<li>cudatoolkit               10.2.89              hfd86e86_1  </li>
<li>cupy-cuda102              9.5.0                    pypi_0    pypi</li>
<li>cycler                    0.10.0                   py38_0  </li>
<li>cytoolz                   0.11.0           py38h7b6447c_0  </li>
<li>dask-core                 2021.10.0          pyhd3eb1b0_0  </li>
<li>dbus                      1.13.18              hb2f20db_0  </li>
<li>debugpy                   1.4.1            py38h295c915_0  </li>
<li>decorator                 5.1.0              pyhd3eb1b0_0  </li>
<li>defusedxml                0.7.1              pyhd3eb1b0_0  </li>
<li>entrypoints               0.3                      py38_0  </li>
<li>expat                     2.4.1                h2531618_2  </li>
<li>fastrlock                 0.8                      pypi_0    pypi</li>
<li>ffmpeg                    4.3                  hf484d3e_0    pytorch</li>
<li>flake8                    3.9.2              pyhd3eb1b0_0  </li>
<li>fontconfig                2.13.1               h6c09931_0  </li>
<li>fonttools                 4.25.0             pyhd3eb1b0_0  </li>
<li>freetype                  2.11.0               h70c0345_0  </li>
<li>fsspec                    2021.8.1           pyhd3eb1b0_0  </li>
<li>giflib                    5.2.1                h7b6447c_0  </li>
<li>glib                      2.69.1               h5202010_0  </li>
<li>gmp                       6.2.1                h2531618_2  </li>
<li>gnutls                    3.6.15               he1e5248_0  </li>
<li>google-auth               2.3.3                    pypi_0    pypi</li>
<li>google-auth-oauthlib      0.4.6                    pypi_0    pypi</li>
<li>grpcio                    1.42.0                   pypi_0    pypi</li>
<li>gst-plugins-base          1.14.0               h8213a91_2  </li>
<li>gstreamer                 1.14.0               h28cd5cc_2  </li>
<li>icu                       58.2                 he6710b0_3  </li>
<li>idna                      3.2                pyhd3eb1b0_0  </li>
<li>imagecodecs               2021.8.26        py38h4cda21f_0  </li>
<li>imageio                   2.9.0              pyhd3eb1b0_0  </li>
<li>importlab                 0.6.1                    pypi_0    pypi</li>
<li>importlib-metadata        4.8.1            py38h06a4308_0  </li>
<li>importlib_metadata        4.8.1                hd3eb1b0_0  </li>
<li>intel-openmp              2021.4.0          h06a4308_3561  </li>
<li>ipydatawidgets            4.2.0                    pypi_0    pypi</li>
<li>ipykernel                 6.4.1            py38h06a4308_1  </li>
<li>ipympl                    0.8.2                    pypi_0    pypi</li>
<li>ipython                   7.29.0           py38hb070fc8_0  </li>
<li>ipython_genutils          0.2.0              pyhd3eb1b0_1  </li>
<li>ipywidgets                7.6.5                    pypi_0    pypi</li>
<li>isort                     5.9.3              pyhd3eb1b0_0  </li>
<li>itk-core                  5.2.1.post1              pypi_0    pypi</li>
<li>itk-filtering             5.2.1.post1              pypi_0    pypi</li>
<li>itk-meshtopolydata        0.7.1                    pypi_0    pypi</li>
<li>itk-numerics              5.2.1.post1              pypi_0    pypi</li>
<li>itkwidgets                0.32.1                   pypi_0    pypi</li>
<li>jedi                      0.18.0           py38h06a4308_1  </li>
<li>jinja2                    3.0.2              pyhd3eb1b0_0  </li>
<li>joblib                    1.1.0              pyhd3eb1b0_0  </li>
<li>jpeg                      9d                   h7f8727e_0  </li>
<li>json5                     0.9.6              pyhd3eb1b0_0  </li>
<li>jsonschema                3.2.0              pyhd3eb1b0_2  </li>
<li>jupyter_client            7.0.1              pyhd3eb1b0_0  </li>
<li>jupyter_core              4.8.1            py38h06a4308_0  </li>
<li>jupyter_server            1.4.1            py38h06a4308_0  </li>
<li>jupyterlab                3.2.1              pyhd3eb1b0_1  </li>
<li>jupyterlab-widgets        1.0.2                    pypi_0    pypi</li>
<li>jupyterlab_pygments       0.1.2                      py_0  </li>
<li>jupyterlab_server         2.8.2              pyhd3eb1b0_0  </li>
<li>jxrlib                    1.1                  h7b6447c_2  </li>
<li>kiwisolver                1.3.1            py38h2531618_0  </li>
<li>krb5                      1.19.2               hac12032_0  </li>
<li>lame                      3.100                h7b6447c_0  </li>
<li>lcms2                     2.12                 h3be6417_0  </li>
<li>ld_impl_linux-64          2.35.1               h7274673_9  </li>
<li>lerc                      3.0                  h295c915_0  </li>
<li>libaec                    1.0.4                he6710b0_1  </li>
<li>libcst                    0.3.21                   pypi_0    pypi</li>
<li>libcurl                   7.78.0               h0b77cf5_0  </li>
<li>libdeflate                1.8                  h7f8727e_5  </li>
<li>libedit                   3.1.20210910         h7f8727e_0  </li>
<li>libev                     4.33                 h7f8727e_1  </li>
<li>libffi                    3.3                  he6710b0_2  </li>
<li>libgcc-ng                 9.3.0               h5101ec6_17  </li>
<li>libgfortran-ng            7.5.0               ha8ba4b0_17  </li>
<li>libgfortran4              7.5.0               ha8ba4b0_17  </li>
<li>libgomp                   9.3.0               h5101ec6_17  </li>
<li>libiconv                  1.15                 h63c8f33_5  </li>
<li>libidn2                   2.3.2                h7f8727e_0  </li>
<li>libnghttp2                1.41.0               hf8bcb03_2  </li>
<li>libpng                    1.6.37               hbc83047_0  </li>
<li>libsodium                 1.0.18               h7b6447c_0  </li>
<li>libssh2                   1.9.0                h1ba5d50_1  </li>
<li>libstdcxx-ng              9.3.0               hd4cf53a_17  </li>
<li>libtasn1                  4.16.0               h27cfd23_0  </li>
<li>libtiff                   4.2.0                h85742a9_0  </li>
<li>libunistring              0.9.10               h27cfd23_0  </li>
<li>libuuid                   1.0.3                h7f8727e_2  </li>
<li>libuv                     1.40.0               h7b6447c_0  </li>
<li>libwebp                   1.2.0                h89dd481_0  </li>
<li>libwebp-base              1.2.0                h27cfd23_0  </li>
<li>libxcb                    1.14                 h7b6447c_0  </li>
<li>libxml2                   2.9.12               h03d6c58_0  </li>
<li>libzopfli                 1.0.3                he6710b0_0  </li>
<li>locket                    0.2.1            py38h06a4308_1  </li>
<li>lz4-c                     1.9.3                h295c915_1  </li>
<li>markdown                  3.3.6                    pypi_0    pypi</li>
<li>markupsafe                2.0.1            py38h27cfd23_0  </li>
<li>matplotlib                3.4.3            py38h06a4308_0  </li>
<li>matplotlib-base           3.4.3            py38hbbc1b5f_0  </li>
<li>matplotlib-inline         0.1.2              pyhd3eb1b0_2  </li>
<li>mccabe                    0.6.1                    py38_1  </li>
<li>mistune                   0.8.4           py38h7b6447c_1000  </li>
<li>mkl                       2021.4.0           h06a4308_640  </li>
<li>mkl-service               2.4.0            py38h7f8727e_0  </li>
<li>mkl_fft                   1.3.1            py38hd3c417c_0  </li>
<li>mkl_random                1.2.2            py38h51133e4_0  </li>
<li>monai                     0.7.0                    pypi_0    pypi</li>
<li>munkres                   1.1.4                      py_0  </li>
<li>mypy                      0.910              pyhd3eb1b0_0  </li>
<li>mypy_extensions           0.4.3                    py38_0  </li>
<li>nbclassic                 0.2.6              pyhd3eb1b0_0  </li>
<li>nbclient                  0.5.3              pyhd3eb1b0_0  </li>
<li>nbconvert                 6.1.0            py38h06a4308_0  </li>
<li>nbformat                  5.1.3              pyhd3eb1b0_0  </li>
<li>ncurses                   6.3                  heee7806_1  </li>
<li>nest-asyncio              1.5.1              pyhd3eb1b0_0  </li>
<li>nettle                    3.7.3                hbbd107a_1  </li>
<li>networkx                  2.6.3              pyhd3eb1b0_0  </li>
<li>nibabel                   3.2.1                    pypi_0    pypi</li>
<li>ninja                     1.10.2.2                 pypi_0    pypi</li>
<li>notebook                  6.4.5            py38h06a4308_0  </li>
<li>numexpr                   2.7.3            py38h22e1b3c_1  </li>
<li>numpy                     1.21.2           py38h20f2e39_0  </li>
<li>numpy-base                1.21.2           py38h79a1101_0  </li>
<li>oauthlib                  3.1.1                    pypi_0    pypi</li>
<li>olefile                   0.46               pyhd3eb1b0_0  </li>
<li>openh264                  2.1.0                hd408876_0  </li>
<li>openjpeg                  2.4.0                h3ad879b_0  </li>
<li>openssl                   1.1.1l               h7f8727e_0  </li>
<li>packaging                 21.0               pyhd3eb1b0_0  </li>
<li>pandas                    1.3.4            py38h8c16a72_0  </li>
<li>pandocfilters             1.4.3            py38h06a4308_1  </li>
<li>param                     1.12.0                   pypi_0    pypi</li>
<li>parameterized             0.8.1              pyhd3eb1b0_1  </li>
<li>parso                     0.8.2              pyhd3eb1b0_0  </li>
<li>partd                     1.2.0              pyhd3eb1b0_0  </li>
<li>pathspec                  0.7.0                      py_0  </li>
<li>pcre                      8.45                 h295c915_0  </li>
<li>pexpect                   4.8.0              pyhd3eb1b0_3  </li>
<li>pickleshare               0.7.5           pyhd3eb1b0_1003  </li>
<li>pillow                    8.4.0            py38h5aabda8_0  </li>
<li>pip                       21.2.4           py38h06a4308_0  </li>
<li>prometheus_client         0.11.0             pyhd3eb1b0_0  </li>
<li>prompt-toolkit            3.0.20             pyhd3eb1b0_0  </li>
<li>protobuf                  3.19.1                   pypi_0    pypi</li>
<li>psutil                    5.8.0            py38h27cfd23_1  </li>
<li>ptyprocess                0.7.0              pyhd3eb1b0_2  </li>
<li>pyasn1                    0.4.8                    pypi_0    pypi</li>
<li>pyasn1-modules            0.2.8                    pypi_0    pypi</li>
<li>pycodestyle               2.7.0              pyhd3eb1b0_0  </li>
<li>pycparser                 2.20                       py_2  </li>
<li>pyct                      0.4.8                    pypi_0    pypi</li>
<li>pyflakes                  2.3.1              pyhd3eb1b0_0  </li>
<li>pygments                  2.10.0             pyhd3eb1b0_0  </li>
<li>pyopenssl                 21.0.0             pyhd3eb1b0_1  </li>
<li>pyparsing                 3.0.4              pyhd3eb1b0_0  </li>
<li>pyqt                      5.9.2            py38h05f1152_4  </li>
<li>pyrsistent                0.18.0           py38heee7806_0  </li>
<li>pysocks                   1.7.1            py38h06a4308_0  </li>
<li>python                    3.8.12               h12debd9_0  </li>
<li>python-dateutil           2.8.2              pyhd3eb1b0_0  </li>
<li>pytorch                   1.10.0          py3.8_cuda10.2_cudnn7.6.5_0    pytorch</li>
<li>pytorch-ignite            0.4.7                    pypi_0    pypi</li>
<li>pytorch-mutex             1.0                        cuda    pytorch</li>
<li>pytype                    2021.11.18               pypi_0    pypi</li>
<li>pytz                      2021.3             pyhd3eb1b0_0  </li>
<li>pywavelets                1.1.1            py38h7b6447c_2  </li>
<li>pyyaml                    6.0              py38h7f8727e_1  </li>
<li>pyzmq                     22.2.1           py38h295c915_1  </li>
<li>qt                        5.9.7                h5867ecd_1  </li>
<li>readline                  8.1                  h27cfd23_0  </li>
<li>regex                     2021.8.3         py38h7f8727e_0  </li>
<li>requests                  2.26.0             pyhd3eb1b0_0  </li>
<li>requests-oauthlib         1.3.0                    pypi_0    pypi</li>
<li>rsa                       4.8                      pypi_0    pypi</li>
<li>scikit-image              0.18.3           py38h51133e4_0  </li>
<li>scikit-learn              1.0.1            py38h51133e4_0  </li>
<li>scipy                     1.7.1            py38h292c36d_2  </li>
<li>send2trash                1.8.0              pyhd3eb1b0_1  </li>
<li>setuptools                58.0.4           py38h06a4308_0  </li>
<li>sip                       4.19.13          py38he6710b0_0  </li>
<li>six                       1.16.0             pyhd3eb1b0_0  </li>
<li>snappy                    1.1.8                he6710b0_0  </li>
<li>sniffio                   1.2.0            py38h06a4308_1  </li>
<li>sqlite                    3.36.0               hc218d9a_0  </li>
<li>tabulate                  0.8.9                    pypi_0    pypi</li>
<li>tensorboard               2.7.0                    pypi_0    pypi</li>
<li>tensorboard-data-server   0.6.1                    pypi_0    pypi</li>
<li>tensorboard-plugin-wit    1.8.0                    pypi_0    pypi</li>
<li>terminado                 0.9.4            py38h06a4308_0  </li>
<li>testpath                  0.5.0              pyhd3eb1b0_0  </li>
<li>threadpoolctl             2.2.0              pyh0d69192_0  </li>
<li>tifffile                  2021.7.2           pyhd3eb1b0_2  </li>
<li>tk                        8.6.11               h1ccaba5_0  </li>
<li>toml                      0.10.2             pyhd3eb1b0_0  </li>
<li>toolz                     0.11.1             pyhd3eb1b0_0  </li>
<li>torchinfo                 1.5.3                    pypi_0    pypi</li>
<li>torchvision               0.11.1               py38_cu102    pytorch</li>
<li>tornado                   6.1              py38h27cfd23_0  </li>
<li>traitlets                 5.1.0              pyhd3eb1b0_0  </li>
<li>traittypes                0.2.1                    pypi_0    pypi</li>
<li>typed-ast                 1.5.0                    pypi_0    pypi</li>
<li>typing-inspect            0.7.1                    pypi_0    pypi</li>
<li>typing_extensions         3.10.0.2           pyh06a4308_0  </li>
<li>urllib3                   1.26.7             pyhd3eb1b0_0  </li>
<li>wcwidth                   0.2.5              pyhd3eb1b0_0  </li>
<li>webencodings              0.5.1                    py38_1  </li>
<li>werkzeug                  2.0.2                    pypi_0    pypi</li>
<li>wheel                     0.37.0             pyhd3eb1b0_1  </li>
<li>widgetsnbextension        3.5.2                    pypi_0    pypi</li>
<li>xz                        5.2.5                h7b6447c_0  </li>
<li>yaml                      0.2.5                h7b6447c_0  </li>
<li>zeromq                    4.3.4                h2531618_0  </li>
<li>zfp                       0.5.5                h2531618_6  </li>
<li>zipp                      3.6.0              pyhd3eb1b0_0  </li>
<li>zlib                      1.2.11               h7b6447c_3  </li>
<li>zstandard                 0.16.0                   pypi_0    pypi</li>
<li>zstd                      1.4.9                haebb681_0  </li>
</ul>
</details>

**Comment by aylward** [comment]
I've sent an invite to Matt McCormick to join this project.  He might have insights.

**Comment by aylward** [comment]
Hmm - can you try with non-tensor data?

Perhaps try any of the examples at
https://github.com/InsightSoftwareConsortium/itkwidgets/tree/master/examples

Sorry for the inconvenience and thanks for your persistence!

**Comment by ericspod** [comment]
It was actually Numpy arrays and not tensors. I tried the following in Jupyter notebook which was taken from [the 2D example](https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/examples/2DImage.ipynb) but the only output I get is three instances of "libpng warning: sCAL: invalid unit".

```python
from urllib.request import urlretrieve
import os
import itk
from itkwidgets import view

# Download data
file_name = 'cthead1.png'
if not os.path.exists(file_name):
    url = 'https://data.kitware.com/api/v1/file/57b5d9ef8d777f10f269538f/download'
    urlretrieve(url, file_name)

image = itk.imread(file_name)
view(image)
```

**Comment by ericspod** [comment]
Looking at the Javascript console I'm seeing some errors related to JQuery amongst other things:

image

**Comment by aylward** [comment]
Thanks!

I've forwarded to Matt.  Fingers crossed.

S

**Review by wyli — APPROVED** [review]
Thanks, I think this could be an initial demo, and we can refine it later

**Comment by Nic-Ma** [comment]
Hi @ericspod @aylward @wyli ,

Thanks for the review and comments.
I updated the PR to use `PLS` orientation and it depends on PR https://github.com/Project-MONAI/MONAI/pull/3385.
@wyli and I also verified the itkwidgets view online.

Thanks.

**Pull request merged**
