### PR TITLE
Add TensorBoardStatsHandler for 2d_classfication

### LINKED ISSUE #1649: Add TensorBoardStatsHandler in 2d_classfication
Add tensorboard handler in https://github.com/Project-MONAI/tutorials/tree/main/2d_classification

### PR DESCRIPTION
**Pull request by KumoLiu**
Fixes #1649

### Description

Add TensorBoardStatsHandler for 2d_classfication

### Checks

- [ ] Avoid including large-size files in the PR.
- [ ] Clean up long text outputs from code cells in the notebook.
- [ ] For security purposes, please check the contents and remove any sensitive info such as user names and private key.
- [ ] Ensure (1) hyperlinks and markdown anchors are working (2) use relative paths for tutorial repo files (3) put figure and graphs in the `./figure` folder
- [ ] Notebook runs automatically `./runner.sh -t <path to .ipynb file>`

### CODE REVIEW

**Comment by ericspod** [comment]
Extending from our conversation just now on a MONAI 201 notebook, I used this pattern with the bundle tutorials with [03_mednist_classification_v2.ipynb](https://github.com/Project-MONAI/tutorials/blob/main/bundle/03_mednist_classification_v2.ipynb). This is the pattern I'd suggest of a lesson building on a previous one.

**Comment by KumoLiu** [comment]
Hi @ericspod, do you think for this one we also need to add another tutorial since there only three lines were added?
https://github.com/Project-MONAI/tutorials/blob/39ecb41b480cf2438a3e3d4da9119a2cc26b89a1/2d_classification/mednist_tutorial.ipynb

**Comment by ericspod** [comment]
> Hi @ericspod, do you think for this one we also need to add another tutorial since there only three lines were added?
> https://github.com/Project-MONAI/tutorials/blob/39ecb41b480cf2438a3e3d4da9119a2cc26b89a1/2d_classification/mednist_tutorial.ipynb

For this notebook maybe these additions are fine, the monai_101.ipynb was the super-simple notebook I wanted to keep small. Since you're using Tensorboard, is there something that can be added to demonstrate that data within the notebook? I don't know if including [Tensorboard in the notebook](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks) will render correctly in Github.

**Comment by KumoLiu** [comment]
> Since you're using Tensorboard, is there something that can be added to demonstrate that data within the notebook? I don't know if including [Tensorboard in the notebook](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks) will render correctly in Github.

Hi @ericspod, I have added this part, could you please help review it again, thanks!

**Review by ericspod — APPROVED** [review]
Looks good to me!

**Pull request merged**
