### PR TITLE
Experiment Management Tutorial

### LINKED ISSUE #817: Experiments management with AIM and MLFlow
**Is your feature request related to a problem? Please describe.**
Investigate AIM and MLFlow workflow and try to apply in the MONAI training experiments.
Refer to: https://aimstack.io/aim-monai-tutorial/

### PR DESCRIPTION
**Pull request by yuchen-xu**
Fixes #817.

### Description
Studying and developing tutorials for experiment management from Aim and MLFlow.

IMPORTANT:
This PR should not be merged without consulting the Aim team, since the code is partly [theirs](https://github.com/osoblanco/tutorials/blob/master/3d_segmentation/spleen_segmentation_3d.ipynb).

### Status
**Work in progress**

### Checks
- [x] Notebook runs automatically `./runner -p "-name aim_tutorial.ipynb"`

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Part of the milestone: https://github.com/Project-MONAI/MONAI/milestone/57.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @yuchen-xu ,

I think there is too much change in this PR, could you please help clean it?
image

Thanks.

**Comment by Nic-Ma** [comment]
Please remove the `Check transforms in DataLoader` section in the notebook, I think we should keep the notebook simpler to only show the experiment management tools.
For rich information of the spleen training, users can check the original 3D segmentation tutorial.

Thanks.

**Comment by Nic-Ma** [comment]
1. May I know what these 2 lines for:
```py
rlimit = resource.getrlimit(resource.RLIMIT_NOFILE)
resource.setrlimit(resource.RLIMIT_NOFILE, (4096, rlimit[1]))
```
2. I see very long code in the notebook for `plotly_3d_figure`, can you use this `matshow3d` function instead?
https://github.com/Project-MONAI/MONAI/blob/dev/monai/visualize/utils.py#L30
3. I think the very long change is due to your screenshot images in the notebook, maybe your method is not correct, please paste the image in the jupyter notebook directly.

Thanks.

**Comment by yuchen-xu** [comment]
1. This sets a lower (soft) limit for the maximum number of open file descriptors. I'm not exactly sure what they do in this tutorial either, so I'm removing them for now. If it's ever needed in the future, the code to do that is preserved above.
2. I will be using an alternative method of visualization in place of plotly.
3. The count of line changes is due to the 3D plotly interactive figure. I've removed that now. The screenshots, while appears long in raw data, are taking up one line each. I checked the original spleen 3D tutorial and fast training tutorial, and their screenshots are all like this (basically pasted directly onto here). This is clearly not the most elegant design, so I think there are a few options if you want to make the **raw** notebook look better:
a) Put all screenshots on a website (githubusercontent, amazonaws, etc.) and link to them
b) Put all screenshots in their own folder, in a subfolder called "images" (or something else)
c) Put all screenshots in tutorials/images, but this will be an issue if the user launches the notebook from a subfolder rather than the main tutorial folder, since relative file paths will fail
d) Keep them the way they are (a very long one-line in raw data, but fine in normal Jupyter display).
4. Done.

**Comment by wyli** [comment]
thanks, my main concern is -- the tutorials all look like pytorch/ignite+mlflow/aim examples, the value added by monai is unclear... any idea how to highlight some domain specific capability? just some ideas may or may not work:
- experiments tracking + configuration based training (https://github.com/Project-MONAI/tutorials/tree/main/modules/bundle/hybrid_programming)
- might be interesting to track dataset summary info which includes some metadata (https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/dataset_summary.py)
- track versions of persistent cache datasets from monai

**Review by Nic-Ma — APPROVED** [review]
Hi @yuchen-xu ,

Thanks for the quick update.
As the 3D visualization is important feature in these 2 notebooks, could you please help add one more screenshot about the visualization result in AIM and MLFlow based on your blend function?

@wyli Thanks for your great suggestions, we will develop more experiment management tutorials to show the combination with **MONAI bundle** and **workflows**. For example, AIM has support for ignite:
https://aimstack.readthedocs.io/en/latest/quick_start/integrations.html?highlight=ignite#integration-with-pytorch-ignite

Thanks.

**Pull request merged**
