### PR TITLE
Update profiling code with NVTX handlers

### PR DESCRIPTION
**Pull request by drbeh**
### Description
This PR update the NVTX profiling to include NVTX handlers, and also update the `RangePush`/`RangePop` to the simpler interface of `Range`.

This requires [MONAI/PR2765](https://github.com/Project-MONAI/MONAI/pull/2765) to be merged first. 

### Status
**Ready**

### CODE REVIEW

**Comment by drbeh** [comment]
@Nic-Ma @wyli, this notebook is ready to be reviewed/merged.

**Comment by drbeh** [comment]
As I mentioned in #308, this notebook now tries to download two large histopathology images. Although the runner should work but it might take a while depending on the server speed (about 1 hour). Do you want me to exclude it from `runner.sh` again or it's fine since it is a cron job?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I feel 1 hour is acceptable for cron job, but it should be stable enough.
What do you think?

Thanks.

**Review by Nic-Ma — APPROVED** [review]

**Comment by drbeh** [comment]
I saw that the cron job has 150min timeout for all the notebook. I'll move things to our google drive (instead of outside ftp) to speed up the download.

**Comment by drbeh** [comment]
@Nic-Ma @wyli, 
I updated the notebook and now it's only doing profiling for training (not validation) and only with the smallest Camelyon tumor image. I moved the image to our google drive and now it's very fast to download and depending on internet speed it should take more than few minutes.

I don't have write access to this repo so can any of you merge it. Thanks

**Review by wyli — APPROVED** [review]
Thanks for enhancing the tests!

**Pull request merged**
