### PR TITLE
Add unet++ notebook

### PR DESCRIPTION
**Pull request by nhhung1810**
Fixes https://github.com/Project-MONAI/tutorials/issues/1475.

### Description
A few sentences describing the changes proposed in this pull request.

### Checks

- [x] Avoid including large-size files in the PR.
- [x] Clean up long text outputs from code cells in the notebook.
- [x] For security purposes, please check the contents and remove any sensitive info such as user names and private key.
- [x] Ensure (1) hyperlinks and markdown anchors are working (2) use relative paths for tutorial repo files (3) put figure and graphs in the `./figure` folder
- [x] Notebook runs automatically `./runner.sh -t <path to .ipynb file>`

### CODE REVIEW

**Comment by wyli** [comment]
thanks, please follow this https://github.com/Project-MONAI/tutorials/blob/main/CONTRIBUTING.md#create-a-notebook to create the necessary cells, I think you can copy them from https://github.com/Project-MONAI/tutorials/blob/main/modules/UNet_input_size_constrains.ipynb

**Comment by mingxin-zheng** [comment]
Thank you @nhhung1810 for the PR. I just started to read the notebook. I noticed that there are many commented code, and the last cell has outputs from all-commented code block. May I know what the commented code is for?

**Comment by nhhung1810** [comment]
Hey @mingxin-zheng , that commented code is for exploration on the implementation of UNET++. I'll delete it after the other things resolved

**Comment by wyli** [comment]
thanks! would be great to have a conclusion section to recommend the usage, for example, about how to set number of downsampling layesr and input spatial sizes, and the normalisation argument might require a tuple for additional parameters https://github.com/Project-MONAI/MONAI/blob/6f5cea3795278c20568261ebb38907d94b576b98/monai/networks/nets/daf3d.py#L490-L491. the current notebook explores many tests but it's unclear to me what are the suitable configurations for this model.

**Comment by nhhung1810** [comment]
Sure @wyli, I'll dig into the original papers and others papers to write the conclusion. Also, I'll include a network image for reference

**Review by wyli — APPROVED** [review]
Thanks, it looks good to me.

**Pull request merged**
