### PR TITLE
Tutorial/Demo for Modular Patch Inferer

### PR DESCRIPTION
**Pull request by drbeh**
### Description
This PR adds a notebook to demonstrate how the new [modular patch inference](https://github.com/Project-MONAI/MONAI/issues/5837) can used:
- `PatchInferer`
- `AvgMerger`
- `SlidingWindowSplitter`
- `WSISlidingWindowSplitter`

### Checks

- [x] Avoid including large-size files in the PR.
- [x] Clean up long text outputs from code cells in the notebook.
- [x] For security purposes, please check the contents and remove any sensitive info such as user names and private key.
- [x] Ensure (1) hyperlinks and markdown anchors are working (2) use relative paths for tutorial repo files (3) put figure and graphs in the `./figure` folder
- [x] Notebook runs automatically `./runner.sh -t <path to .ipynb file>`

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @drbeh , do you plan to complete this PR for review?

Thanks.

**Comment by drbeh** [comment]
> Hi @drbeh , do you plan to complete this PR for review?
> 
> Thanks.

Yes, I'll do it shortly.

**Comment by drbeh** [comment]
We might need to wait for the next `monai-weekly` release before merging this notebook.

**Comment by Nic-Ma** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/Project-MONAI/tutorials/pull/1316/discussion/#comment-1574811979) on ReviewNB
> 
> _Nic-Ma commented on 2023-06-03T09:32:29Z_ ----------------------------------------------------------------
> 
> I think we usually don't need to put the program code design diagram in tutorial, what do you think?
> 
> Thanks.

@wyli @ericspod What do you think?

Thanks.

**Comment by ericspod** [comment]
> > View / edit / reply to [this conversation](https://app.reviewnb.com/Project-MONAI/tutorials/pull/1316/discussion/#comment-1574811979) on ReviewNB
> > _Nic-Ma commented on 2023-06-03T09:32:29Z_ ----------------------------------------------------------------
> > I think we usually don't need to put the program code design diagram in tutorial, what do you think?
> > Thanks.
> 
> @wyli @ericspod What do you think?
> 
> Thanks.

I'm fine with more information in tutorials especially for a design concept that requires a little explanation. We can do embedded images directly in the notebook rather than linking to a file if you wanted to not have it.  Thanks!

**Comment by drbeh** [comment]
@KumoLiu @Nic-Ma please let me know if you have any other comments.

**Review by Nic-Ma — APPROVED** [review]

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

I see 1 error in the CI:
```
    510 elif self.backend == "openslide":
--> 511     self.reader = OpenSlideWSIReader(
    512         level=level,
    513         mpp=mpp,
    514         mpp_rtol=mpp_rtol,
    515         mpp_atol=mpp_atol,
    516         power=power,
    517         power_rtol=power_rtol,
    518         power_atol=power_atol,
    519         channel_dim=channel_dim,
    520         dtype=dtype,
    521         device=device,
    522         mode=mode,
    523         **kwargs,
    524     )
    525 elif self.backend == "tifffile":
    526     self.reader = TiffFileWSIReader(
    527         level=level,
    528         mpp=mpp,
   (...)
    538         **kwargs,
    539     )

File /opt/conda/lib/python3.8/site-packages/monai/utils/module.py:488, in require_pkg.<locals>._decorator.<locals>._wrapper(*args, **kwargs)
    486 err_msg = f"required package `{pkg_name}` is not installed or the version doesn't match requirement."
    487 if raise_error:
--> 488     raise OptionalImportError(err_msg)
    489 else:
    490     warnings.warn(err_msg)

OptionalImportError: required package `openslide` is not installed or the version doesn't match requirement.


Check failed!
```
If you have any questions about the CI execution env, maybe @mingxin-zheng and @wyli can help.

Thanks in advance.

**Comment by drbeh** [comment]
> Hi @drbeh ,
> 
> I see 1 error in the CI:
> 
> ```
>     510 elif self.backend == "openslide":
> --> 511     self.reader = OpenSlideWSIReader(
>     512         level=level,
>     513         mpp=mpp,
>     514         mpp_rtol=mpp_rtol,
>     515         mpp_atol=mpp_atol,
>     516         power=power,
>     517         power_rtol=power_rtol,
>     518         power_atol=power_atol,
>     519         channel_dim=channel_dim,
>     520         dtype=dtype,
>     521         device=device,
>     522         mode=mode,
>     523         **kwargs,
>     524     )
>     525 elif self.backend == "tifffile":
>     526     self.reader = TiffFileWSIReader(
>     527         level=level,
>     528         mpp=mpp,
>    (...)
>     538         **kwargs,
>     539     )
> 
> File /opt/conda/lib/python3.8/site-packages/monai/utils/module.py:488, in require_pkg.<locals>._decorator.<locals>._wrapper(*args, **kwargs)
>     486 err_msg = f"required package `{pkg_name}` is not installed or the version doesn't match requirement."
>     487 if raise_error:
> --> 488     raise OptionalImportError(err_msg)
>     489 else:
>     490     warnings.warn(err_msg)
> 
> OptionalImportError: required package `openslide` is not installed or the version doesn't match requirement.
> 
> 
> Check failed!
> ```
> 
> If you have any questions about the CI execution env, maybe @mingxin-zheng and @wyli can help.
> 
> Thanks in advance.

That's right, @Nic-Ma! I believe openslide library is not being installed in the CI/CD. I can add it but let me see if I can make things work with cucim, so we can avoid additional time that installing the library will take for each test.

**Comment by drbeh** [comment]
It passed all tests with cucim. Will merge it.

**Pull request merged**
