### PR TITLE
Update Tumor Detection Profiling for v0.8.1

### PR DESCRIPTION
**Pull request by drbeh**
Partly addresses #565 

### Description
Update and verify tumor detection pipeline with MONAI v0.8.1 (https://github.com/Project-MONAI/tutorials/pull/568)

### Status
**Ready**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by yiheng-wang-nv** [comment]
Hi @drbeh , thanks for the updates. Could you try to avoid changing the outputs of cells and only change the code itself? Otherwise it is not convenient to check the differences.

**Comment by drbeh** [comment]
> Hi @drbeh , thanks for the updates. Could you try to avoid changing the outputs of cells and only change the code itself? Otherwise it is not convenient to check the differences.

Right! GitHub doesn't have the best tools to diff jupyter notebooks. We shouldn't keep the output unchanged while they are depending on the changed code. Anyways, for the sake of reviewing this notebook, you just need to run it and see if it is working.

**Comment by yiheng-wang-nv** [comment]
> We shouldn't keep the output unchanged while they are depending on the changed code

Hi @drbeh , you can check the commits history and most of the changes are only for the code itself. Iike what I did in #565

>  for the sake of reviewing this notebook, you just need to run it and see if it is working

If so, all reviewers need to run all notebooks every time to avoid checking thousands of diffs.

HI @wyli @Nic-Ma , could you please how to double confirm it? Thanks!

**Comment by wyli** [comment]
Normally if there's no major change we often keep the previous output, it doesn't add much burden to the git history size and review becomes straightforward. That's really considerate. But I guess it's difficult to enforce this rule for every PR.

**Review by wyli — APPROVED** [review]
Thanks, it looks good to me.

**Comment by drbeh** [comment]
> > We shouldn't keep the output unchanged while they are depending on the changed code
> 
> Hi @drbeh , you can check the commits history and most of the changes are only for the code itself. Iike what I did in #565
> 
> > for the sake of reviewing this notebook, you just need to run it and see if it is working
> 
> If so, all reviewers need to run all notebooks every time to avoid checking thousands of diffs.
> 
> HI @wyli @Nic-Ma , could you please how to double confirm it? Thanks!

@yiheng-wang-nv, I agree with you! What I typically do is to keep the outputs intact for each commit and re-run the affected outputs only at the last commit. In this way, we can compare to the one-to-the-last commit for checking the differences while using the last one to merging (assuming the last one only have changes in the outputs).
However, in this notebook, changing the code only and saving the notebook made so many changes in the metadata, which seems to be re-ordering of fields mainly. I think it was due to the difference in the version of jupyter engines.

Anyways, I agree that we should be more mindful of the changes in the notebooks for an easier review.

**Pull request merged**
