### PR TITLE
change folder name generative to generation

### PR DESCRIPTION
**Pull request by Can-Zhao**
Fixes # .

### Description
change folder name generative to generation

### Checks

- [ ] Avoid including large-size files in the PR.
- [ ] Clean up long text outputs from code cells in the notebook.
- [ ] For security purposes, please check the contents and remove any sensitive info such as user names and private key.
- [ ] Ensure (1) hyperlinks and markdown anchors are working (2) use relative paths for tutorial repo files (3) put figure and graphs in the `./figure` folder
- [ ] Notebook runs automatically `./runner.sh -t <path to .ipynb file>`

### CODE REVIEW

**Comment by ericspod** [comment]
We've always called it "Generative AI", I think the name makes sense to refer to that term though it differs from many other names in tutorials currently. Was there a particular reason you thought this needed renaming? We should check no URLs get broken by this, eg. Colab links in notebooks.

**Comment by Can-Zhao** [comment]
> We've always called it "Generative AI", I think the name makes sense to refer to that term though it differs from many other names in tutorials currently. Was there a particular reason you thought this needed renaming? We should check no URLs get broken by this, eg. Colab links in notebooks.

I remember there was concern when people import package `generative` and import the function under this folder `generative` at the same time. There might be potential risk

**Comment by KumoLiu** [comment]
Hi @Can-Zhao, thanks for the pr, please also updated related "Setup environment" section.
https://github.com/Project-MONAI/tutorials/blob/main/generative/maisi/maisi_inference_tutorial.ipynb
https://github.com/Project-MONAI/tutorials/blob/main/generative/maisi/maisi_train_vae_tutorial.ipynb

And @ericspod, yes, just like what Can mentioned, the main issue here is that `import generative` will cause conflict. Do you have more concern to change these folder names? Thanks!

**Comment by Can-Zhao** [comment]
> Hi @Can-Zhao, thanks for the pr, please also updated related "Setup environment" section. https://github.com/Project-MONAI/tutorials/blob/main/generative/maisi/maisi_inference_tutorial.ipynb https://github.com/Project-MONAI/tutorials/blob/main/generative/maisi/maisi_train_vae_tutorial.ipynb
> 
> And @ericspod, yes, just like what Can mentioned, the main issue here is that `import generative` will cause conflict. Do you have more concern to change these folder names? Thanks!

Hi Yun, the `generative ` imported in notebooks are from generative repo, not this tutorial generative.

**Comment by KumoLiu** [comment]
> Hi Yun, the `generative ` imported in notebooks are from generative repo, not this tutorial generative.

I know, I mean remove the print statement which is temporarily used to avoid the conflict.

**Comment by ericspod** [comment]
> I remember there was concern when people import package `generative` and import the function under this folder `generative` at the same time. There might be potential risk. Changing folder name is a low-cost solution to avoid such risk

My understanding then is if someone imports "generative" with the current working directory as the root of this repo, they'll import the directory here "generative" rather than the GenerativeModels module. That seems a valid concern, even though GenerativeModels is going to become archived when the porting process is done it will still be used. I'm good with this change, thanks.

**Comment by Can-Zhao** [comment]
> > Hi Yun, the `generative ` imported in notebooks are from generative repo, not this tutorial generative.
> 
> I know, I mean remove the print statement which is temporarily used to avoid the conflict.

Done

**Comment by Can-Zhao** [comment]
> > I remember there was concern when people import package `generative` and import the function under this folder `generative` at the same time. There might be potential risk. Changing folder name is a low-cost solution to avoid such risk
> 
> My understanding then is if someone imports "generative" with the current working directory as the root of this repo, they'll import the directory here "generative" rather than the GenerativeModels module. That seems a valid concern, even though GenerativeModels is going to become archived when the porting process is done it will still be used. I'm good with this change, thanks.

Thanks

**Review by ericspod — APPROVED** [review]
I'm good if others are. Thanks!

**Review by KumoLiu — APPROVED** [review]

**Pull request merged**
