### PR TITLE
Fix minor description typo in UNETR tutorial

### PR DESCRIPTION
**Pull request by ahatamiz**
### Description
This fixes fix a minor description typo in UNETR tutorial.

### Status
Ready

### Checks

- [x] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @ahatamiz ,

Could you please help resolve the conflicts?
Thanks in advance.

**Comment by ahatamiz** [comment]
> Hi @ahatamiz ,
> 
> Could you please help resolve the conflicts?
> Thanks in advance.

Hi @Nic-Ma  it seems like I don't have permission to resolve the conflict here. It's basically a typo correction in descriptions. Would appreciate it if you can please resolve it. 
Thanks again.

**Comment by Nic-Ma** [comment]
Hi @ahatamiz ,

As the code has big conflicts now, I can't see the real modification.
Could you please delete this PR and submit a new one based on the **latest master branch** code?
Then you will not have conflicts I think.

Thanks in advance.

**Comment by ahatamiz** [comment]
Hi @Nic-Ma,

Sure. I can close this PR and submit a new one. But just to understand, currently I see 1 conflict which is the typo fix in line 21. Would you please let me know what big conflict you see on your end ? 

Thanks again

**Comment by Nic-Ma** [comment]
Hi @ahatamiz ,

I used an online tool to check the conflicts, now I can't see it as you closed the PR.
Anyway, thanks for your new PR, I already merged it.

Thanks.

**Comment by ahatamiz** [comment]
Hi @Nic-Ma , Sure. Makes sense. 

Thanks again

**Pull request closed without merging**
