### PR TITLE
Update acceleration tutorials for MetaTensor

### LINKED ISSUE #782: Update acceleration tutorials for MetaTensor
**Is your feature request related to a problem? Please describe.**
For compatibility with MONAI 0.9.1 onwards.

### PR DESCRIPTION
**Pull request by yuchen-xu**
Fixes #782 .

### Status
**Work in progress**

### Checks
- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @yuchen-xu ,

Did you see any performance drop in the `fast training pipeline` when you switched from `0.9.0` to `0.9.1`?

Thanks.

**Comment by yuchen-xu** [comment]
@Nic-Ma Thanks a lot for the suggestion. I tried it and here's what I got:
0.9.1rc3 Original: 314.19s Optimized: 21.78s
0.9.0      Original: 278.79s Optimized: 13.00s

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Seems 0.9.1rc3 is much slower, especially for the optimized pipeline?

Thanks.

**Comment by wyli** [comment]
yes I've addressed some deepcopy issues in https://github.com/Project-MONAI/MONAI/pull/4709, will tag a new release candidate for testing. this PR looks good.

**Review by wyli — APPROVED** [review]

**Comment by Nic-Ma** [comment]
I tested the training speed on V100 with MONAI 0.9.0 and latest dev (after 0.9.1rc3):
average speed of 1 epoch: 0.9.0=1.74s, dev=1.8s
Maybe we can continue to optimize MetaTensor operations in the future versions.

Thanks.

**Pull request merged**
