### PR TITLE
config cachedatset for dataset_type_performance

### LINKED ISSUE #1214: Compare results in `dataset_type_performance.ipynb`
**Is your feature request related to a problem? Please describe.**
From the results of [this comparison experiment](https://github.com/Project-MONAI/tutorials/blob/1.0.0/acceleration/dataset_type_performance.ipynb), why the time of `CacheDataset` is slower than `PersistentDataset` for each epoch of training? Users may not easily understand the advantages of `CacheDataset` from these results.

image

**Describe the solution you'd like**
The results in tag 1.0.0 are more make sense.
image
 
cc @wyli @Nic-Ma

### PR DESCRIPTION
**Pull request by wyli**
Fixes #1214

### Description
update the cachedatset config to improve the performance

### Checks

- [x] Avoid including large-size files in the PR.
- [x] Clean up long text outputs from code cells in the notebook.
- [x] For security purposes, please check the contents and remove any sensitive info such as user names and private key.
- [x] Ensure (1) hyperlinks and markdown anchors are working (2) use relative paths for tutorial repo files (3) put figure and graphs in the `./figure` folder
- [x] Notebook runs automatically `./runner.sh -t <path to .ipynb file>`

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

May I know the root cause of the performance issue? Why `image_only` can help improve the `CacheDataset` than `persistentDataset`?
And BTW, if you want to show `runtime_cache` feature in this tutorial, please update the plot figure to remove the `init cache` part.

Thanks.

**Comment by wyli** [comment]
Yes, the root cause is the cache init being slow, and maybe related to  https://github.com/Project-MONAI/MONAI/issues/5930.

image_only will remove the additional unnecessary meta_dict and the warning message. It doesn't change the relative speed comparisons.

We should keep cache_init, because the cache dataset still have the option of precompute the cache, the user can experiment and plot.

**Comment by Nic-Ma** [comment]
OK, could you please help add some description or comment in the notebook to explain the "runtime_cache" usage and `init_cache` plot? I feel confused when I see the plot chart which has `init_cache time = 0`.
Others look good to me.

Thanks in advance.

**Comment by dongyang0122** [comment]
If `image_only` is important to showcase advantages of PersistentDataset, I would suggest to add few words under the section of PersistentDataset explaining it? The rest of the content looks great.

**Review by dongyang0122 — APPROVED** [review]

**Pull request merged**
