### PR TITLE
Update "pathology/tumor_detection/ignite/profiling_camelyon_pipeline.ipynb"

### PR DESCRIPTION
**Pull request by KumoLiu**
Fixes # .

### Description
Update the usage of nvtx in "tumor_detection_camelyon"

### Checks

- [ ] Avoid including large-size files in the PR.
- [ ] Clean up long text outputs from code cells in the notebook.
- [ ] For security purposes, please check the contents and remove any sensitive info such as user names and private key.
- [ ] Ensure (1) hyperlinks and markdown anchors are working (2) use relative paths for tutorial repo files (3) put figure and graphs in the `./figure` folder
- [ ] Notebook runs automatically `./runner.sh -t <path to .ipynb file>`

### CODE REVIEW

**Review by drbeh — APPROVED** [review]
Thanks @KumoLiu! I have tested it on my machine and all works fine.

**Comment by drbeh** [comment]
@KumoLiu I see an error in the CI but I don't see it when running locally. Can it be due the installed nsight version?

**Comment by KumoLiu** [comment]
It’s wired, I don’t see any reason why the file is not exist. Also, what could be the reasons for it not executing immediately.

**Comment by ericspod** [comment]
I would think papermill would run all command invocations otherwise many other notebooks would fail. How large is the generated csv? If the container runs out of space and tries to write the file it may silently do nothing, but this file would have to be really big. We could have a check right after `nsys stats` to check that the file was created: `assert os.path.isfile("profile_report_nvtx_pushpop_sum.csv")`. For testing in the CICD environment we could temporarily add `!ls -lh` right before that to see what the file structure looks like.

**Comment by KumoLiu** [comment]
works well in the 24.02 PyTorch image, close for now.

**Pull request merged**
