### PR TITLE
fix pep 8 for all previously-excluded notebooks

### LINKED ISSUE #1136: PEP8 check should be applied to all notebooks
**Describe the bug**

Currently we use a pre-defined pattern to include/exclude notebooks in the CI/CD.
https://github.com/Project-MONAI/tutorials/blob/f87bb12f1140962d415b83163143ba6f898904a0/runner.sh#L73

Because some notebooks need user inputs (e.g. preparing a dataset manually), we should not use `papermill` to automate the execution in the CI/CD. However, the pattern also allows these notebook to skip the PEP8 check, which I think should be applied:

https://github.com/Project-MONAI/tutorials/blob/f87bb12f1140962d415b83163143ba6f898904a0/runner.sh#L225

**Suggested Solution**

Add a `skip_run_papermill` pattern to skip the notebooks that's not intended to be part of CI/CD.

```bash
# run papermill
if [ $doRun = true ]; then

	skipRun=false
	
	for skip_pattern in "${skip_run_papermill[@]}"; do
		if [[  $file =~ $skip_pattern ]]; then
			skipRun=true
			break
		fi
	done

	if [ $skipRun = true ]; then
		break
	fi

	echo Running notebook...
	notebook=$(cat "$filename")
    
```

```
skip_run_papermill=()
skip_run_papermill=("${skip_run_papermill[@]}" .*federated_learning*)
skip_run_papermill=("${skip_run_papermill[@]}" .*transchex_openi*)
skip_run_papermill=("${skip_run_papermill[@]}" .*unetr_*)
skip_run_papermill=("${skip_run_papermill[@]}" .*profiling_train_base_nvtx*)
skip_run_papermill=("${skip_run_papermill[@]}" .*benchmark_global_mutual_information*)
skip_run_papermill=("${skip_run_papermill[@]}" .*spleen_segmentation_3d_visualization_basic*)
skip_run_papermill=("${skip_run_papermill[@]}" .*full_gpu_inference_pipeline*)
skip_run_papermill=("${skip_run_papermill[@]}" .*generate_random_permutations*)
skip_run_papermill=("${skip_run_papermill[@]}" .*transforms_update_meta_data*)
skip_run_papermill=("${skip_run_papermill[@]}" .*video_seg*)
skip_run_papermill=("${skip_run_papermill[@]}" .*tcia_dataset*)
skip_run_papermill=("${skip_run_papermill[@]}" .*hovernet_torch*)
skip_run_papermill=("${skip_run_papermill[@]}" .*preprocess_detect_scene_and_split_fold*)
skip_run_papermill=("${skip_run_papermill[@]}" .*preprocess_to_build_detection_dataset*)
skip_run_papermill=("${skip_run_papermill[@]}" .*preprocess_extract_images_from_video*)
skip_run_papermill=("${skip_run_papermill[@]}" .*transfer_mmar*)
skip_run_papermill=("${skip_run_papermill[@]}" .*MRI_reconstruction*)
```
**Expected behavior**
PEP 8 check on all notebooks

### PR DESCRIPTION
**Pull request by mingxin-zheng**
Signed-off-by: Mingxin Zheng <18563433+mingxin-zheng@users.noreply.github.com>

Fixes #1136 .

### Description
The PR expands the scope of PEP 8 checks to cover some notebooks there were previously excluded

### Checks

- [x] Notebook runs automatically `./runner --no-run`

### CODE REVIEW

**Review by wyli — APPROVED** [review]

**Comment by wyli** [comment]
please be careful when fixing the new pep8 issues, there's no automated tests to verify the code changes...

**Comment by mingxin-zheng** [comment]
Hi @wyli , I start to do some manual checks on the notebooks that I touched. The coverage will be limited, and I can see some notebook outside the coverage is not running correctly, like this one #1139 .

Between fixing the bug in this PR or in another PR, I am inclined to the latter if it is not caused by my changes, so that we can make the PR as atomic as possible.

**Comment by wyli** [comment]
sure, this looks good to me, if @Nic-Ma doesn't have any other comments let's merge it first.

**Comment by Nic-Ma** [comment]
Hi @binliunls @mingxin-zheng ,

Will this PR conflict with https://github.com/Project-MONAI/tutorials/pull/1100?
Just a reminder.

Thanks.

**Comment by mingxin-zheng** [comment]
@binliunls my edits here rearrange some code blocks in `video_seg.ipynb` to pass PEP 8 checks. If your PR can be merged soon, maybe I can wait and merge yours to mine. The other way also works (merge mine then yours) for me.

**Comment by binliunls** [comment]
> @binliunls my edits here rearrange some code blocks in `video_seg.ipynb` to pass PEP 8 checks. If your PR can be merged soon, maybe I can wait and merge yours to mine. The other way also works (merge mine then yours) for me.

You can merge first. I will then merge your update to my repo.

**Comment by mingxin-zheng** [comment]
Thanks @binliunls , I have just merged mine to the `main`.

**Pull request merged**
