### PR TITLE
Update fast training tutorial

### LINKED ISSUE #312: Update the fast_training tutorial with latest solution
**Is your feature request related to a problem? Please describe.**
Recently, we spent much time optimizing the performance of spleen training, got obvious improvement in:
https://github.com/Project-MONAI/tutorials/blob/master/acceleration/fast_training_tutorial.ipynb

Will try to update it when the multi-threads cropping finalized:
https://github.com/Project-MONAI/MONAI/issues/2794

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #312 #313 .

### Description
This PR updated the fast training tutorial with the latest solutions and enhanced charts.

### Status
**Ready**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Review by rijobro — COMMENTED** [review]
Looks great! Thanks

**Comment by wyli** [comment]
there's also the same type of errors in the amp tutorial, https://github.com/Project-MONAI/tutorials/blob/master/acceleration/automatic_mixed_precision.ipynb, do you want to do it in this PR or in another followup?

**Review by wyli — APPROVED** [review]
thanks, would be great to fix all the notebooks as we are testing the blossom pipeline

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Sure, I also updated the AMP tutorial to fix #313 , I think no other tutorial or example left.

Thanks.

**Pull request merged**
