### PR TITLE
341 Add TCIA loading tutorial

### LINKED ISSUE #341: Add TCIA data loading tutorial with CSVDataset
**Is your feature request related to a problem? Please describe.**
This is a sub-task of https://github.com/Project-MONAI/MONAI/issues/2877
Will load TCIA data from CSV file and use the link to get image data from REST API.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #341 .

### Description
This PR added the tutorial to load TCIA CSV file and execute the following processing.

### Status
**Ready**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your review.
I updated the tutorial based on your comments.
Could you please help review it again?

Thanks.

**Comment by wyli** [comment]
thanks, it looks nice to me. @kirbyju could you please help review this notebook? https://github.com/Project-MONAI/tutorials/blob/82e1e623c2cfaad3b3dd94db537bb743dce523a6/modules/tcia_csv_processing.ipynb

(for the tag issue, you can use https://gist.github.com/edrohler/7a0c2ed0db15db768271, maybe the root cause is that your fork doesn't have all the tags from the core codebase)

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I have updated the PR based on online comments, could you please help review it again?

Thanks in advance.

**Review by wyli — APPROVED** [review]

**Comment by wyli** [comment]
Might want to make a copy of the CSV data to our shared drive? https://drive.google.com/drive/u/2/folders/1ZOqwF44newvq-jOSgnbXRDWRD9DRq8hH

**Comment by Nic-Ma** [comment]
> Might want to make a copy of the CSV data to our shared drive? https://drive.google.com/drive/u/2/folders/1ZOqwF44newvq-jOSgnbXRDWRD9DRq8hH

Hi @wyli ,

Thanks for your suggestion.
I think this CSV file only works for this first step as a temp file(hand-made and only the first lines is useful), we can upload to MONAI google drive later when we have a finalized version for real-world training tutorial.
What do you think?

Thanks.

**Pull request merged**
