### PR TITLE
[WIP] NuClick Tutorial

### PR DESCRIPTION
**Pull request by finalelement**
Signed-off-by: vnath <vnath@nvidia.com>

### Description
Adding NuClick Tutorial based on upcoming integrations to MONAI Core.

### Status
**Work in progress**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by finalelement** [comment]
I think these look reasonable, I can do some more polishing perhaps. 

@wyli please check it out

@SachidanandAlle please provide some more thoughts for the visualization of transforms, if we need them.

**Comment by finalelement** [comment]
@SachidanandAlle Thanks, will add the suggested kind of explanation for inference ..

@wyli I'll reach out again after updating Sachi's comments

**Comment by finalelement** [comment]
@SachidanandAlle please check the changes. 

@wyli Tests are running locally, will push again once tests finish etc.

**Comment by SachidanandAlle** [comment]
LGTM

**Comment by finalelement** [comment]
@wyli all tests cleared, thank you for the support

**Comment by finalelement** [comment]
@wyli nuclick tests excluded from runner.sh as suggested. Links for pre-trained weight has also been added.

**Review by wyli — APPROVED** [review]
Thanks, it looks good to me.

**Pull request merged**
