### PR TITLE
copy tcia model zoo tutorial

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

originally released at https://github.com/kirbyju/TCIA_Notebooks/blob/main/TCIA_MONAI_Model_Zoo.ipynb

(adapting it to monai tutorials' coding style cc @kirbyju)

### Checks

- [ ] Avoid including large-size files in the PR.
- [ ] Clean up long text outputs from code cells in the notebook.
- [ ] For security purposes, please check the contents and remove any sensitive info such as user names and private key.
- [ ] Ensure (1) hyperlinks and markdown anchors are working (2) use relative paths for tutorial repo files (3) put figure and graphs in the `./figure` folder
- [ ] Notebook runs automatically `./runner.sh -t <path to .ipynb file>`

### CODE REVIEW

**Comment by kirbyju** [comment]
<p>Can you change the file name on this to something like "TCIA_PROSTATEx_Prostate_MRI_Anatomy_Model.ipynb"?  I think this will help keep things organized as I'm hoping we'll be adding more "TCIA Dataset + MONAI Model" notebooks in the near future to provide functioning demonstrations of other models in the zoo.  </p>

**Comment by wyli** [comment]
sure, I'll do that. the descriptions in the notebook are not very specific to the dataset though.

**Comment by kirbyju** [comment]
What's the best way for me to fix that?  Should I wait for you to merge things to main and then do a pull request to improve the descriptions?

Justin Kirby (contractor)
Technical Project Manager, Frederick National Laboratory for Cancer Research
Technical Director, Cancer Imaging Informatics Lab
ORCiD: https://orcid.org/0000-0003-3487-8922
240-276-6016
***@***.******@***.***>


________________________________
From: Wenqi Li ***@***.***>
Sent: Wednesday, January 18, 2023 11:51 AM
To: Project-MONAI/tutorials ***@***.***>
Cc: Kirby, Justin (NIH/NCI) [C] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Project-MONAI/tutorials] copy tcia model zoo tutorial (PR #1176)


sure, I'll do that. the descriptions in the notebook are not very specific to the dataset though.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProject-MONAI%2Ftutorials%2Fpull%2F1176%23issuecomment-1387382213&data=05%7C01%7Ckirbyju%40mail.nih.gov%7C625aa45ef5d24f4309b308daf9745ff3%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638096575460847926%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mAbRsC%2BXoru1NeO3uuiuN72FqMO%2B%2F0RnnDpg3h9rrmk%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAASE6B5YUXQ4BNYY46PZ2TDWTANSVANCNFSM6AAAAAAT5YIYNQ&data=05%7C01%7Ckirbyju%40mail.nih.gov%7C625aa45ef5d24f4309b308daf9745ff3%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638096575460847926%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=c9KcxARoN7l6YGs1lXWijgX9y8LwzmoSKS%2BQngnyL%2F0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by wyli** [comment]
I haven't spent much time on this PR yet, I think it'll be easier if you could finalise the content first and put it somewhere, then I make simple adjustments to use monai tutorial's coding style and pass the integration tests...

**Comment by kirbyju** [comment]
I submitted a PR.  Are you able to work from that?  I saw all the automated tests failed.  If it's easier you can reject the PR and grab it from https://github.com/kirbyju/tutorials/blob/tcia-prostate-model-zoo/model_zoo/TCIA_PROSTATEx_Prostate_MRI_Anatomy_Model.ipynb.

Justin Kirby (contractor)
Technical Project Manager, Frederick National Laboratory for Cancer Research
Technical Director, Cancer Imaging Informatics Lab
ORCiD: https://orcid.org/0000-0003-3487-8922
240-276-6016
***@***.******@***.***>


________________________________
From: Wenqi Li ***@***.***>
Sent: Wednesday, January 18, 2023 12:06 PM
To: Project-MONAI/tutorials ***@***.***>
Cc: Kirby, Justin (NIH/NCI) [C] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Project-MONAI/tutorials] copy tcia model zoo tutorial (PR #1176)


I haven't spent much time on this PR yet, I think it'll be easier if you could finalise the content first and put it somewhere, then I make simple adjustments to use monai tutorial's coding style and pass the integration tests...

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProject-MONAI%2Ftutorials%2Fpull%2F1176%23issuecomment-1387422592&data=05%7C01%7Ckirbyju%40mail.nih.gov%7C5b4c92033cda460ab35608daf97781f0%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638096588921683686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Pt4Erm1BctjAImItVVCYiBykLxR%2BJDjuqb%2FntdKqiyw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAASE6B5XYV4K2GDRM6HUFCLWTAPI5ANCNFSM6AAAAAAT5YIYNQ&data=05%7C01%7Ckirbyju%40mail.nih.gov%7C5b4c92033cda460ab35608daf97781f0%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638096588921683686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ywmc4WC59GtpAp4kjI10IPpdZec5sqNKtXIpG9GScHc%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by wyli** [comment]
sure, closing this in favor of https://github.com/Project-MONAI/tutorials/pull/1185

**Pull request closed without merging**
