### PR TITLE
adds a configparser example

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

### Status
**Ready**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

May I know why adding this new example? Is there any feature request from users?
I didn't get the difference between this example and the existing inference example.

Thanks.

**Comment by wyli** [comment]
Yes, Dong was asking how to override the config parameters

**Comment by Nic-Ma** [comment]
> Yes, Dong was asking how to override the config parameters

OK, I feel maybe it's better to add `override` feature is the existing inference example, no need a new train example?

Thanks.

**Comment by wyli** [comment]
no, let's keep the concept simple, the demo is just to show a working skeleton about a command line entry point and reading multiple keys and overriding config key-values, the other example show how to set other python function parameters directly.

**Review by Nic-Ma — APPROVED** [review]

**Pull request merged**
