### PR TITLE
covid interpretability

### PR DESCRIPTION
**Pull request by rijobro**
@wyli I was interested to see the interpretability using images that were less zoomed in compared to the lesion example. Not sure what to make of the images yet.

@ericspod Would it be possible to put the covid images somewhere public (e.g., Kaggle/Zenodo)?

### CODE REVIEW

**Comment by wyli** [comment]
just wanted to double check this PR, it's not ready because the x-ray dataset not released publicly?

**Comment by rijobro** [comment]
Hi, that's correct. @ericspod any update on this? Would you like me to see to it?

**Comment by ericspod** [comment]
I have the dataset up now on a Kaggle page: https://www.kaggle.com/ericspod/project-monai-2020-bootcamp-challenge-dataset If this is ok with everyone I will update the bootcamp repo with reference to it and the other materials for the day 3 challenge.

**Comment by rijobro** [comment]
This PR is now ready for review @wyli @ericspod @Nic-Ma . Thanks!

**Review by wyli — APPROVED** [review]
thanks!

**Pull request merged**
