### PR TITLE
Update distributed training for MetaTensor

### PR DESCRIPTION
**Pull request by Nic-Ma**
### Description
This PR updated all the distributed training tutorials to adapt to the `MetaTensor`.

### Status
**Ready**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli , @rijobro ,

I have updated and verified all the distributed training / evaluation examples on 2 V100 GPUs.
Could you please help review it?

Thanks in advance.

**Review by wyli — APPROVED** [review]

**Comment by wyli** [comment]
thanks, could you pls also help review this related https://github.com/Project-MONAI/tutorials/blob/main/modules/compute_metric.py

**Comment by Nic-Ma** [comment]
> thanks, could you pls also help review this related https://github.com/Project-MONAI/tutorials/blob/main/modules/compute_metric.py @Nic-Ma

Sure, I will update it and test soon.

Thanks.

**Comment by Nic-Ma** [comment]
Submitted PR for it:https://github.com/Project-MONAI/tutorials/pull/780

Thanks.

**Pull request merged**
