### PR TITLE
115 add paired ct lung tutorial

### PR DESCRIPTION
**Pull request by kate-sann5100**
Signed-off-by: kate-sann5100 <yiwen.li@st-annes.ox.ac.uk>

### CODE REVIEW

**Comment by wyli** [comment]
couldn't launch the demo on colab with a 16Gb GPU: `CUDA out of memory. Tried to allocate 234.00 MiB (GPU 0; 15.90 GiB total capacity; 14.72 GiB already allocated; 65.06 MiB free; 15.02 GiB reserved in total by PyTorch)`
is it possible to make the demo smaller?

**Comment by wyli** [comment]
here's the link to a colab instance: https://colab.research.google.com/github/Project-MONAI/tutorials/blob/59918536b1bfa3d7723f60ea49dcaa262185961f/3d_registration/paired_lung_ct.ipynb

**Comment by kate-sann5100** [comment]
@wyli Thank you. I will try to fix that.

**Comment by wyli** [comment]
there is a pep8 issue:
```
Running ./3d_registration/paired_lung_ct.ipynb
Checking PEP8 compliance...
stdin:448:1: W391 blank line at end of file

^
Error: Try running with autofixes: --autofix.

Check failed!
```

**Comment by kate-sann5100** [comment]
> there is a pep8 issue:
> 
> ```
> Running ./3d_registration/paired_lung_ct.ipynb
> Checking PEP8 compliance...
> stdin:448:1: W391 blank line at end of file
> 
> ^
> Error: Try running with autofixes: --autofix.
> 
> Check failed!
> ```

error resolved.

**Review by wyli — APPROVED** [review]
thanks!

**Pull request merged**
