### PR TITLE
Add TransCheX Tutorial

### PR DESCRIPTION
**Pull request by ahatamiz**
Signed-off-by: ahatamizadeh <ahatamizadeh@nvidia.com>

### Description
This PR adds the multimodal tutorial for Open-I dataset multilabel disease classification using the TransCheX model.
### Status
**Ready**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by ahatamiz** [comment]
Hi @wyli 

Is there any way to resolve errors like ' module level import not at top of file ' ? I checked the code cells that pertain to this error, but did not see any anti-pattern. All imports are at the top. 

Thanks

**Comment by ahatamiz** [comment]
Hi @wyli and @Nic-Ma 

Is there any way to resolve errors like ' module level import not at top of file ' ? I checked the code cells that pertain to this error, but did not see any anti-pattern. All imports are at the top. 

Thanks for your assistance in advance.

**Comment by wyli** [comment]
> Hi @wyli and @Nic-Ma
> 
> Is there any way to resolve errors like ' module level import not at top of file ' ? I checked the code cells that pertain to this error, but did not see any anti-pattern. All imports are at the top.
> 
> Thanks for your assistance in advance.

I think the formatting requirement is to put all import statements in the first python cell

**Comment by ahatamiz** [comment]
> > Hi @wyli and @Nic-Ma
> > Is there any way to resolve errors like ' module level import not at top of file ' ? I checked the code cells that pertain to this error, but did not see any anti-pattern. All imports are at the top.
> > Thanks for your assistance in advance.
> 
> I think the formatting requirement is to put all import statements in the first python cell

Thank you @wyli. I believe this was a bit different than before where imports could have been done in various cells. But I think the PEP8 requirement is very helpful in keeping all tutorials consistent in terms of the code format. 

As I check have passed, I appreciate your review.

**Comment by ahatamiz** [comment]
Hi @wyli 

Would appreciate your review on this one. 

Thanks

**Review by wyli — COMMENTED** [review]
Thanks, it looks good to me in general. could you please
- remove the author info ([also described here](https://github.com/Project-MONAI/tutorials/issues/434), this is a decision from our dev discussions, the git commit history already tracks the author info.)
- help testing by running `./runner.sh` with a GPU? if it doesn't pass the test, would be great to amend the command here to skip the test: https://github.com/Project-MONAI/tutorials/blob/4e1e316115f101c2c9434b5c7fea27f50cdeb3ef/runner.sh#L61-L65

**Comment by ahatamiz** [comment]
@wyli 

Thanks. I have removed the author info. The tutorial requires downloading and preprocessing of the dataset, hence cannot be automatically tested using `./runner.sh` . As such, I have added this tutorial to the list for skipping this test.

**Review by wyli — APPROVED** [review]
Thanks, it looks good to me.

**Pull request merged**
