### PR TITLE
run modified notebooks

### PR DESCRIPTION
**Pull request by rijobro**
@wyli do you think you'd be able to look at the github action for this? It will only run any modified notebooks, but I'm not sure how to set up the environment so that it has pytorch+cuda.

### CODE REVIEW

**Comment by wyli** [comment]
could discuss this on Friday, two options would be:
- cron tests using github self-hosted runners (those in project-monai/monai and to be shared at the org. level)
- migrate heavy cron CI/CD pipelines to blossom directly for this repo 

cc @IsaacYangSLA @madil90 this is about monai tutorials ci/cd

**Comment by rijobro** [comment]
Little bump on this.

**Comment by wyli** [comment]
tested:
- with notebook change https://github.com/Project-MONAI/tutorials/actions/runs/3225804756/jobs/5278551449
- without notebook change https://github.com/Project-MONAI/tutorials/actions/runs/3225853092/jobs/5278658938

**Review by wyli — APPROVED** [review]
tested with self-hosted

**Comment by rijobro** [comment]
Great, thanks!

**Pull request merged**
