### PR TITLE
Add a visualization tutorial for 3D detection boxes

### PR DESCRIPTION
**Pull request by dongyang0122**
Fixes # .

### Description
Add a visualization tutorial for 3D detection boxes.

### Status
Ready

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

**Comment by Can-Zhao** [comment]
Thank you Dong! I was wondering if it is possible to add an option to indicate whether box is in world coordinate or image coordinate. Because for most dataset, boxes are with image coordinate

**Comment by dongyang0122** [comment]
> Thank you Dong! I was wondering if it is possible to add an option to indicate whether box is in world coordinate or image coordinate. Because for most dataset, boxes are with image coordinate

It is possible. but we need an example data ".json" to figure out the image coordinate systems (e.g., RAS or LPI).

**Comment by dongyang0122** [comment]
@Can-Zhao @wyli any plan to add an example case for coordinates in image coordinate?

**Review by wyli — APPROVED** [review]

**Comment by wyli** [comment]
I think this one has good details, merging it now

**Pull request merged**
