### PR TITLE
91 Update all notebooks to MONAI v0.4

### LINKED ISSUE #91: verify notebooks using the latest monai 0.4.0 pypi release
subtask of https://github.com/Project-MONAI/MONAI/issues/1318
need to 
- check that `pip install monai[all]` works for all the notebooks and demos
- tag a 0.4.0 version of this repo

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #91 

This PR updated all the notebooks to use MONAI v0.4 and removed all the `temp install` cells.
We can tag v0.4 in this repo when it merged.

### CODE REVIEW

**Comment by wyli** [comment]
thanks I tried the first notebook 2d_classification/mednist_tutorial.ipynb and it doesn't work because LoadImage doesn't support '.jpeg'. Have you verified all the notebooks?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Good finding, I didn't run all the notebooks to the end.
Now I am running again.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I tested all the notebooks to the end, all executed as expected, except the 3 MedNIST GAN related:
**mednist_GAN_tutorial.ipynb
mednist_GAN_workflow_array.ipynb
mednist_GAN_workflow_dict.ipynb**
The `CacheDataset` was caching very slow and randomly crash sometimes.
Maybe it's my local env issue, could you please help double confirm it?

Thanks.

**Comment by wyli** [comment]
thanks @Nic-Ma I used the colab button in those notebooks and they don't work: 
```python-traceback
<ipython-input-7-c840c719f5a7> in __call__(self, data)
      2     def __call__(self, data):
----> 3         return plt.imread(tar.extractfile(data))
      4 

/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py in imread(fname, format)
   2060 def imread(fname, format=None):
-> 2061     return matplotlib.image.imread(fname, format)
   2062 

/usr/local/lib/python3.6/dist-packages/matplotlib/image.py in imread(fname, format)
   1463                              'installed, Matplotlib can handle more images')
-> 1464         with Image.open(fname) as image:
   1465             return pil_to_array(image)

/usr/local/lib/python3.6/dist-packages/PIL/Image.py in open(fp, mode)
   2861     raise UnidentifiedImageError(
-> 2862         "cannot identify image file %r" % (filename if filename else fp)
   2863     )

UnidentifiedImageError: cannot identify image file <ExFileObject name='MedNIST.tar.gz'>

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-c840c719f5a7> in <module>()
     16 )
     17 
---> 18 train_ds = CacheDataset(hands, train_transforms)
     19 train_loader = torch.utils.data.DataLoader(
     20     train_ds, batch_size=batch_size, shuffle=True, num_workers=10

/usr/local/lib/python3.6/dist-packages/monai/data/dataset.py in __init__(self, data, transform, cache_num, cache_rate, num_workers)
    490         if self.num_workers is not None:
    491             self.num_workers = max(int(self.num_workers), 1)
--> 492         self._cache: List = self._fill_cache()
    493 
    494     def _fill_cache(self) -> List:

/usr/local/lib/python3.6/dist-packages/monai/data/dataset.py in _fill_cache(self)
    500             if has_tqdm:
    501                 return list(tqdm(p.imap(self._load_cache_item, range(self.cache_num)), total=self.cache_num))
--> 502             return list(p.imap(self._load_cache_item, range(self.cache_num)))
    503 
    504     def _load_cache_item(self, idx: int):

/usr/lib/python3.6/multiprocessing/pool.py in next(self, timeout)
    733         if success:
    734             return value
--> 735         raise value
    736 
    737     __next__ = next                    # XXX

/usr/lib/python3.6/multiprocessing/pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    117         job, i, func, args, kwds = task
    118         try:
--> 119             result = (True, func(*args, **kwds))
    120         except Exception as e:
    121             if wrap_exception and func is not _helper_reraises_exception:

/usr/local/lib/python3.6/dist-packages/monai/data/dataset.py in _load_cache_item(self, idx)
    514             if isinstance(_transform, Randomizable) or not isinstance(_transform, Transform):
    515                 break
--> 516             item = apply_transform(_transform, item)
    517         return item
    518 

/usr/local/lib/python3.6/dist-packages/monai/transforms/utils.py in apply_transform(transform, data, map_items)
    361         return transform(data)
    362     except Exception as e:
--> 363         raise RuntimeError(f"applying transform {transform}") from e
    364 
    365 

RuntimeError: applying transform <__main__.LoadTarJpeg object at 0x7f7b74053b70>
```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I also tested all the examples and submitted fix commit, all passed now(I didn't test distributed training with Horovod).

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I fixed the `MedNIST GAN` issue in the latest commit, and added logic to install MONAI from master code for the 2 notebooks that using `jpeg` format images.
Could you please help review this PR?

Thanks.

**Review by wyli — APPROVED** [review]
thanks @Nic-Ma , I tested that the v0.4.0 loadimage will use the default itk loader for jpeg, which is also fine, just need to add `[itk]` in  the pip command

**Pull request merged**
